services:
  client:
    container_name: client
    image: oracionxi/nextjs_client:v2
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8800
    depends_on:
      - server
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      retries: 3
      timeout: 10s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
