name: Docker Build Check

on:
  push:
    branches:
      - feature/*

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
        continue-on-error: true

      - name: Dry run docker build process
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          if [[ "$BRANCH_NAME" == "feature/backend" ]]; then
            docker build --progress=plain --no-cache -t test-image ./server
          elif [[ "$BRANCH_NAME" == "feature/frontend" ]]; then
            docker build --progress=plain --no-cache -t test-image ./client
          else
            echo "Unsupported branch, skipping build"
            exit 1
          fi

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "test-image"
          format: "table"
          exit-code: 1
          severity: "CRITICAL,HIGH"

  create-pull-request:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')

          if gh pr list --base development --head "$BRANCH_NAME" --state open | grep -q "$BRANCH_NAME"; then
            echo "PR already exists"
          else
            gh pr create \
              --base development \
              --head "$BRANCH_NAME" \
              --title "Auto PR: Merge $BRANCH_NAME into development" \
              --body "This pull request was automatically created by GitHub Actions."
            echo "PR created successfully."
          fi
